### ISSUE TITLE
Fehlermeldung und keine Datenpunkte

### ISSUE THREAD

**Issue by Eistee82** [Schmakus/ioBroker.lightcontrol#124]
![image](https://user-images.githubusercontent.com/1881217/236694302-7e0f1a7b-b296-4dbd-acc6-43bd9c8b0ce7.png)

**Comment by Eistee82** [comment]
![image](https://user-images.githubusercontent.com/1881217/236694571-493e5173-4944-4eda-a946-708bf5e46b77.png)

**Comment by Schmakus** [comment]
Welche Version?

**Comment by Eistee82** [comment]
Steht im 2. Screen da ist der Start des Scripts. Scheinbar fehlt ihm bei mir irgendwas. IOB ist aktuell

**Comment by Schmakus** [comment]
Ja, bug entdeckt. Ich schaue, dass ich es morgen fixe. Danke fürs Feedback.

**Comment by Schmakus** [comment]
sollte mit v.2.0.14 gefixt sein. Bitte testen.

**Comment by Eistee82** [comment]
Funktioniert nun. Vielen Dank

**Comment by Schmakus** [comment]
mit v.2.0.14 gefixt
