### ISSUE TITLE
Name des Lichts sollte ein Dropdown haben

### ISSUE THREAD

**Issue by Eistee82** [Schmakus/ioBroker.lightcontrol#127]
**Describe the bug**  
Name des Licht ist nur ein Textfeld. Dies führt zu Tippfehlern oder Problemen mit Groß- und Kleinschreibung.

**Expected behavior**  
Name des Lichts sollte ein Dropdown Auswahlfeld haben um bereits in der Gruppe verwendete Namen des Lichts auszuwählen. Damit werden fehlerhafte Eingaben vermieden. Noch besser währe es die Namen innerhalb der Gruppe festzulegen so das man keinen Namen mehr in das Feld "Name des Licht" eintippen kann sondern nur aus den vorher definierten Namen auswählen kann.

**Comment by Schmakus** [comment]
Name des Lichts ist ein sogenanntes "AutoComplete" Feld. In Abhängigkeit der Lichtgruppe werden dort die Namen der Lichter vorgeschlagen. 
Jedoch funktioniert dies aufgrund eines Bugs in jsonConfig nicht immer korrekt. Ist bekannt. 
Ein Drop-down ist nicht möglich, da man ja noch weitere Namen hinzufügen muss. 

Siehe Issue #95
