### ISSUE TITLE
Wert für Helligkeitskorrektur wird falsch interpretiert

### ISSUE THREAD

**Issue by Eistee82** [Schmakus/ioBroker.lightcontrol#129]
Hell/Dunkel Wert für Helligkeitskorrektur soll laut der Beschreibung ein Wert in Prozent sein. Stattdessen wird dieser Wert aber als 100% genommen. Heißt wenn ich min auf 0 und max auf 254 stelle und in Wert für Helligkeitskorrektur eine 100 eintrage dann wird bei 100% Helligkeit der Datenpunkt auf 100 statt auf 254 gesteuert. Trage ich 254 in Wert für Helligkeitskorrektur ein entsprechen 100% 254.

**Comment by Schmakus** [comment]
Ok. Es war glaub anders gedacht mit der Korrektur. Und zwar nicht Prozent, weil das für den User schwer zu ermitteln ist. 
Deshalb trägt man dort die gewünschte max. Helligkeit ein. 
Bedeutet, man stellt alle Lampen innerhalb der Gruppe auf die maximale gemeinsame Helligkeit. Dann gibt es Lampen, welche nur 80% haben oder wie bei Hue z.B. 220, anstatt 256. 
Danach ist die Korrektur entsprechend 80 oder 220. 
Die Doku muss ich dahingehend noch anpassen. 
Zu Beginn des Adapters gab es nur die Möglichkeit von 0-100. 0-256 kam erst später dazu. 

Probiere es mal aus und geb mir Rückmeldung, danke!

**Comment by Eistee82** [comment]
Das ist dann doch die Funktion des Max wertes

**Comment by Schmakus** [comment]
Ja. 

Angenommen zu hast 256
Dann entsprechen 100% des Adapters 256 Helligkeit und bei 50% eine Helligkeit von 128. 

Wenn du eine Korrektur von 128 eingibst entsprechen 100% Heiligkeit 128 und bei 50% eine Helligkeit von 64. 

Usw. 

Normalerweise könnte man sich die Korrektur sparen indem man gleich den entsprechenden Wert bei Max einträgt, jedoch soll bei Putzlicht alles auf maximale Helligkeit gehen. Aber dafür fehlt noch eine Funktionsänderung habe ich bemerkt. 😂
Danke für den Denkanstoß!

**Comment by Eistee82** [comment]
Mach doch für die Korrektur einfach zwei Felder eins in Prozent und eins in absolut. Wenn du in einem der beiden den Wert änderst kannst du den Wert des anderen Felds berechnen und aktualisieren. Somit kann man entweder in Prozent oder in Absolut die Korrektur eingeben. Min und Max macht finde ich ja generell mehr Sinn wenn man das in den normalen Datenpunkt Einstellungen vordefiniert. Evtl. kann man ja die Oberfläche vom Adapter dazu nehmen um die normalen Datenpunktparameter zu setzen. so könnte man auch auf die Schnelle die Helligkeit usw. korrekt definieren ohne aus der rießen liste auswählen zu müssen.

**Comment by Schmakus** [comment]
Die Instanzeinstellungen des Adapters können aufgrund der Komplexität nicht verwendet werden.
Dafür ist die custom config des jeweiligen Datenpunks ideal. 
Meiner Erfahrung nach wird das einmalig eingestellt und dann nie wieder.
