### ISSUE TITLE
min Wert wird nicht korrekt gesetzt

### ISSUE THREAD

**Issue by Eistee82** [Schmakus/ioBroker.lightcontrol#148]
**Describe the bug**  
![image](https://github.com/Schmakus/ioBroker.lightcontrol/assets/1881217/62d3ae0b-51e2-4a08-95eb-777698db7598)

**Expected behavior**  
Wert aus den Einstellungen wird nicht übernommen
![image](https://github.com/Schmakus/ioBroker.lightcontrol/assets/1881217/40232016-d571-4afd-bb2f-93d86dfda1c5)

**Screenshots & Logfiles**  
`{
  "type": "state",
  "common": {
    "read": true,
    "write": true,
    "name": {
      "en": "Colortemperature",
      "de": "Farbtemperatur",
      "ru": "Цветная температура",
      "pt": "Temperatura de cor",
      "nl": "Colortemperatuur",
      "fr": "Colortemperature",
      "it": "Coloratemperature",
      "es": "Colortemperatura",
      "pl": "Colortemperatura",
      "uk": "Кольори",
      "zh-cn": "法定人数"
    },
    "type": "number",
    "role": "level.color.temperature",
    "def": 3300,
    "min": 2100,
    "max": 6500,
    "unit": "K"
  },
  "native": {},
  "_id": "lightcontrol.0.Schlafzimmer.ct",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.eistee",
  "ts": 1688502545739
}`

**Versions:**  
 - Adapter version: 0.2.17
 - JS-Controller version: 5.0.6
 - Node version: 18.16.1
 - Operating system: debian

**Comment by Schmakus** [comment]
Hast du den min-Wert in den Einstellungen geändert, nachdem die Gruppe angelegt wurde?
Wenn ja, dann ist es ein bug, welcher aber nur eine ioBroker-Warnung auswirft. Sollte kein aktuell kein Problem sein.

**Comment by Eistee82** [comment]
Wenn ich den min Wert im Datenpunkt auf 2000 Stelle und den Adapter neu starte steht wieder 2100 da.

**Comment by Schmakus** [comment]
Hi, die min/max Werte des ct-Datenpunkts sind aktuell hart im Code gesetzt.
In einem nächsten Release werde ich das ändern. Bis dahin die js-controller Warnung ignorieren. Danke.
