### ISSUE TITLE
Umkehrung der Farbtemperatur berechnung ohne Funktion

### ISSUE THREAD

**Issue by thoml95** [Schmakus/ioBroker.lightcontrol#149]
**Describe the bug**  
Ändern des Verhaltens der Farbtemperatur funktioniert nicht.

**Expected behavior**  
Das umschalten zwischen "Warmweiß bis Kaltweiß" und "Tageslicht bis Warmweiß" sollte min und max umdrehen.

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

Im Objekt der Lampe unter "ct" fehlt "CtReverse".
`      {
        "description": "Schreibtisch",
        "power": {
          "oid": "homekit-controller.0.IP-15:1D:83:50:AA:EA.1.lightbulb-11.on",
          "onVal": true,
          "offVal": false
        },
        "bri": {
          "oid": "homekit-controller.0.IP-15:1D:83:50:AA:EA.1.lightbulb-11.brightness",
          "minVal": 30,
          "maxVal": 100,
          "defaultBri": 100,
          "useBri": false
        },
        "ct": {
          "oid": "homekit-controller.0.IP-15:1D:83:50:AA:EA.1.lightbulb-11.color-temperature",
          "minVal": 208,
          "maxVal": 400,
          "sendCt": true
        }
      }`

**Versions:**  
 - Adapter version: v0.2.16
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by Schmakus** [comment]
Yep, In den params.js fehlt der Parameter "CtReverse".
