### ISSUE TITLE
Homekit Farbtemperatur auswahl

### ISSUE THREAD

**Issue by thoml95** [Schmakus/ioBroker.lightcontrol#150]
Für Leuchtmittel unter Homekit funktioniert die lineare Skalierung nur mit Abweichung, da dort anders gerechnet wird.

> The corresponding value is an integer representing the color temperature in micro-reciprocal degrees (mired), which is 1,000,000 divided by the color temperature in kelvins. For example, to emulate a traditional tungsten light with a color temperature of 3200 K, use a mired value of about 312.

Wäre es möglich bei der Auswahl "Verhalten der Farbtemperatur" noch z.B. Homekit o.ä. hinzuzufügen? Min und Max müssten aber bleiben, da es auch Leuchtmittel gibt die von Apples min und max abweichen.

**Comment by Schmakus** [comment]
Ich denke, dass bezieht sich nicht nur auf HomeKit. Aktuell wird stumpf umgerechnet. Evtl. macht es Sinn zu wählen, ob es sich beim Datenpunkt um mired, kelvin oder Prozent handelt. Entsprechend dann die Umrechnung.

**Comment by thoml95** [comment]
Eigentlich lässt sich ja so wie es jetzt ist schon viel abdecken, zumindest alles was skaliert wird, noch das mired dazu und dann hat man ja das Meiste.

Evtl. wäre es aber nicht schlecht bei jeder Lampe neben der min und max Farbtemperatur in den Einstellungen noch min und max vergeben zu können.

Sinn dahinter: 
Ich habe eine Schreibtischleuchte von Xiaomi die nimmt mired Werte von 208 - 400, entspricht 4800 - 2500 Kelvin und eine Ambientebeleuchtung von Livarno die nimmt 153 - 500, entspricht 6500 - 2000 Kelvin.
Egal wie ich jetzt min und max in den Einstellungen setze, eine Lampe wird immer die falsche Farbtemperatur haben. Es müsste also einmal der Bereich für den Datenpunkt und einmal der Temperatur bereich vorgegeben werden.

EDIT: Hätte jetzt sonst beides lauffähig.

**Comment by Schmakus** [comment]
Hi, erstmal danke für deine Mitarbeit.
Was passiert, wenn du dir die min/max werte der Lampen auf Basis von 2000 - 6500K errechnest?
Also wenn 208 - 400 => 4800 - 2500 Kelvin entsprechen, dann müsstest bei min/max => 154 - 500 eintragen.

Andere Frage: Wenn die Umrechnung so wie in deinem PR implementiert wird, haben die Lampen dennoch unterschiedliche Farbtemperaturen, bei 2000K oder 6500K, da manche Lampen diese Werte nicht akzeptieren.

Wenn ich mir dahingehend Gedanken mache, komme ich eher zum Ergebnis, eine device.js zu erstellen, mit den Informationen der einzelnen Lampen und deren Adaptern. Dann könnte man es soweit treiben, dass nicht jeder einzelne Datenpunkt jeder Lampe eingestellt werden muss, sondern nur die übergeordnete Device-ID mit Angabe, um welche Lampe und Adapter es sich handelt. Der Adapter zieht sich dann alle DPs (brightness, ct, color, etc) selbst.
Für den normalen User ist es schwer, alle Werte der Lampen zu kennen.

**Comment by thoml95** [comment]
> Hi, erstmal danke für deine Mitarbeit. Was passiert, wenn du dir die min/max werte der Lampen auf Basis von 2000 - 6500K errechnest? Also wenn 208 - 400 => 4800 - 2500 Kelvin entsprechen, dann müsstest bei min/max => 154 - 500 eintragen.
> 
Hi, ja die Beispiele auf basis der mired Werte zu nennen war fehl am platz, da geht das nämlich. Aber bei allen (mir bis jetzt bekannten) Arten muss der Ausgangswert auf die Farbtemperatur passen. Mir ist jetzt aber noch ein denkfehler aufgefallen, ich ändere die anstehenden sachen heute nachmittag/abend.

> Andere Frage: Wenn die Umrechnung so wie in deinem PR implementiert wird, haben die Lampen dennoch unterschiedliche Farbtemperaturen, bei 2000K oder 6500K, da manche Lampen diese Werte nicht akzeptieren.
> 
Ja genau, die werden dann auf ihren max bzw. min Wert beschränkt aber zumindest mit der richtigen Farbtemperatur.

> Wenn ich mir dahingehend Gedanken mache, komme ich eher zum Ergebnis, eine device.js zu erstellen, mit den Informationen der einzelnen Lampen und deren Adaptern. Dann könnte man es soweit treiben, dass nicht jeder einzelne Datenpunkt jeder Lampe eingestellt werden muss, sondern nur die übergeordnete Device-ID mit Angabe, um welche Lampe und Adapter es sich handelt. Der Adapter zieht sich dann alle DPs (brightness, ct, color, etc) selbst. Für den normalen User ist es schwer, alle Werte der Lampen zu kennen.
>
Klingt an sich ganz gut, würde aber z.B. bei meinen zwei hier genanten schon scheitern.. 
Die haben entweder keine min/max Werte oder falsche Grenzen. Müsste also ein Mix aus beidem werden.

EDIT: Hab da am Freitag auf einer langen Autofahrt mal drüber nach gedacht. Für die Farbtemperatur wird das ja generel nicht funktionieren solange diese nicht in Kelvin oder Mired angegeben ist. Im Datenpunkt steht dann ja der min/max Wert für den Datenpunkt und nicht für die Farbtemperatur an sich.

**Comment by Schmakus** [comment]
supported with v.0.3.0
