### ISSUE TITLE
autoOnMotion.enabled = false

### ISSUE THREAD

**Issue by Eistee82** [Schmakus/ioBroker.lightcontrol#152]
autoOnMotion.enabled ist auf false gestellt und trotzdem schaltet der Bewegungsmelder die Lampe an. Ich musste gestern Abend den Adapter stoppen um mein Schlafzimmer dunkel zu bekommen...

Es ist nicht eine autoOn... funktion enabled. Alles auf false

Adapter 0.3.0

**Comment by Schmakus** [comment]
Hi, wird geprüft. Wurde eigentlich nichts daran geändert. Aber man weiß ja nie...

**Comment by Schmakus** [comment]
noch aktuell?
