### ISSUE TITLE
Ausschaltwert wird überschrieben

### ISSUE THREAD

**Issue by mrjeschke** [Schmakus/ioBroker.lightcontrol#17]
Wenn ich bei den Lampeneinstellungen einen Einschaltwert true eingebe und einen Auschaltwert false,
dann die config speichere und schließe und danach wieder öffne, steht in beiden Einstellungen ein true.

**Comment by Schmakus** [comment]
Hi, ja stimmt, ist repro. schau ich mir heute Abend an.

**Comment by Schmakus** [comment]
fixed mit 0.0.4
