### ISSUE TITLE
Which data points for Hue devices

### ISSUE THREAD

**Issue by Moo1988** [Schmakus/ioBroker.lightcontrol#178]
Hello,
I try in vain to insert a Hue bulb.
No matter what I do, the light comes on when there is movement, but the color/temperature is not right.

Can someone tell me the correct data points and what settings they need to be provided with?

In Advance thank you

![hue](https://github.com/Schmakus/ioBroker.lightcontrol/assets/121163101/73bcd3b4-7676-4cdb-880f-8e204ebf011f)

**Comment by Schmakus** [comment]
Sorry for the late answer:
ct = Color Temperatur, Kelvin
xy = color 
Level = brightness 0-100
on = power Switch
