### ISSUE TITLE
2. Lampe nur Power möglich und umbenennen

### ISSUE THREAD

**Issue by Tratonis** [Schmakus/ioBroker.lightcontrol#18]
Neue Gruppe erstellt, 
1. Lampe mit "Decke 1"  erstellt.
Power, Helligkeit und Farbtemperatur hinzugefügt.
Sensor hinzugefügt
2. Lampe mit "Decke 2" erstellt
Power lässt sich hinzufügen, die restlichen Datenpunkte lassen sich nicht aktivieren

Weiteres Problem.
Habe dann versucht die 2. Lampe umzubenennen in Decke_2, daraufhin waren beide Lampen ohne Name
![config](https://user-images.githubusercontent.com/45138214/181354574-86a1b71b-1912-44e6-ad32-791baae0849a.PNG)

**Comment by Schmakus** [comment]
fixed with 0.0.5
