### ISSUE TITLE
Licht State Objekt wird nicht True, obwohl Gruppe isMotion auf True geht

### ISSUE THREAD

**Issue by MichaelUray** [Schmakus/ioBroker.lightcontrol#194]
Ich habe einmal einen Bewegungsmelder und
![2024-02-25_17-17-58_objects_-_iob0_–_Mozilla_Firefox](https://github.com/Schmakus/ioBroker.lightcontrol/assets/25169478/4d1af103-b226-4a53-ae3c-dc4149cbf7e0)

einmal den State eines Lichts mit einer Gruppe verknüpft.

![2024-02-25_17-17-33_objects_-_iob0_–_Mozilla_Firefox](https://github.com/Schmakus/ioBroker.lightcontrol/assets/25169478/37aeba1b-f771-42fc-89ca-4b783a3664cd)

Doch aus irgend einem Grund wird der Objekt-Status des Lichts nicht auf True gesetzt wenn der BWM auslöst.

![2024-02-25_17-19-17_objects_-_iob0_–_Mozilla_Firefox](https://github.com/Schmakus/ioBroker.lightcontrol/assets/25169478/a25f0aa3-c6d9-4aa4-97f2-fffaab3acd89)

Im Log wird auch angezeigt, dass der BWM die Gruppe eigentlich einschaltet, trotzdem wird der Status des Lichts nicht True. Setze ich diesen manuell, setze ich diesen manuell, dann wird er sofort True.
```
lightcontrol.0 | 2024-02-25 17:18:58.394 | info | [ Controller ] Reaching, Group="Kueche1" Property="isMotion" NewVal="true", OldVal=true"
lightcontrol.0 | 2024-02-25 17:17:05.540 | info | [ Controller ] Reaching, Group="Kueche1" Property="isMotion" NewVal="false", OldVal=false"
lightcontrol.0 | 2024-02-25 17:16:33.423 | info | [ Controller ] Reaching, Group="Kueche1" Property="isMotion" NewVal="true", OldVal=true"
lightcontrol.0 | 2024-02-25 17:13:25.315 | info | [ Controller ] Reaching, Group="Kueche1" Property="isMotion" NewVal="false", OldVal=false"
lightcontrol.0 | 2024-02-25 17:12:23.603 | info | [ Controller ] Reaching, Group="Kueche1" Property="isMotion" NewVal="true", OldVal=true"
```

Wie könnte ich hier noch weiter Fehler suchen / debuggen?

**Comment by Schmakus** [comment]
Scheint ein Problem mit neuer und alter Wert zu sein. 
Adapter Version?
Schaue ich
Mir nach meinem Urlaub an.

**Comment by MichaelUray** [comment]
> Adapter Version?

0.4.0

**Comment by Schmakus** [comment]
Hi, kannst du bitte hier einen debug log posten. 
Hinweis 1: ```lightcontrol.0.Esszimmer.autoOnMotion.enabled``` muss natürlich auf ```true``` stehen.
Hinweis 2: Ausschalten mit Sensor geht nur über ```autoOffTimed```. Der Timer wird bei Sensor = ```true```gestartet. Bei jedem weiteren ```true``` wird der Timer zurückgesetzt und erneut gestartet. Sollte nach Ablauf des Timers der Sensor immer noch ```true```sein, wird der Timer ebenfalls neu gestartet.
Bedeutet, sollte der Sensor innerhalb des Timers auf ```false```wechseln, wird dennoch auf Ablauf des Timers gewartet.

**Comment by MichaelUray** [comment]
> Hinweis 1: `lightcontrol.0.Esszimmer.autoOnMotion.enabled` muss natürlich auf `true` stehen.

omg, das war tatsächlich das Problem.
Ist [hier](https://github.com/Schmakus/ioBroker.lightcontrol/blob/main/docs/de/lightcontrol.md#62-datenpunkte-der-einzelnen-gruppe) auch gut beschrieben, RTFM.

Nach mehreren Updates hatte ich verschiedene Probleme und dabei hatte ich einmal auch alle Lichtgruppen gelöscht und wieder angelegt, dabei muss es wohl irgendwie passiert sein.

Sorry und vielen Dank für deine Hilfe!
