### ISSUE TITLE
Umbenennen von Lampen

### ISSUE THREAD

**Issue by Tratonis** [Schmakus/ioBroker.lightcontrol#20]
**Describe the bug**  
Wenn man bei mehreren Lampe eine umbenennt werden alle umbenannt

**To Reproduce**  
2 Lampen in einer Gruppe mit unterschiedlichen Namen anlegen (Decke_1 und Decke_2)
beliebige Lampe umbenennen

**Versions:**  
 - Adapter version: 0.0.5
 - JS-Controller version: 4.0.23
 - Node version: v16.16.0
 - Operating system:  Ubuntu 20.04.4 LTS

**Comment by Schmakus** [comment]
Die Entwicklung des Adapters wird nochmals neu aufgerollt.
