### ISSUE TITLE
request neuer Datenpunkt (zb isMotionAny)

### ISSUE THREAD

**Issue by dannyv1101** [Schmakus/ioBroker.lightcontrol#208]
Ein neuer Datenpunkt für Gruppen mit mehreren Bewegungsmeldern wäre schön. Damit man ohne zusätzliches Skript Lampen schalten kann, wenn nur ein Bewegungsmelder auslöst. Da der Datenpunkt isMotion nur auslöst, wenn alle Bewegungsmelder der Grupper aktiv sind. 

Zb wenn man an einer Treppe onen und unten einen Bewegungsmelder hat, und die Lampe(n) schalten will egal welcher der beiden Bewegungsmelder auslöst.

**Comment by Schmakus** [comment]
Hallo. Es ist so, dass wenn einer der Sensoren auslöst, das Licht angehen sollte. 
Poste mal nen debug log. 

Welche Adapter version?
