### ISSUE TITLE
nur Power ab 2. Lampe

### ISSUE THREAD

**Issue by Tratonis** [Schmakus/ioBroker.lightcontrol#21]
**Describe the bug**  
Datenpunkte lassen sich nicht aktivieren, nur Power ist möglich ab 2. Lampe

**To Reproduce**  
Gruppe anlegen
2 Lampen hinzufügen
Helligkeit bei 1. Lampe anklicken -> geht
Helligkeit bei 2. Lampe anklicken -> lässt sich nicht aktivieren

**Expected behavior**  
Jeder Datenpunkt ist bei jeder Lampe aktivierbar

**Versions:**

- Adapter version: 0.0.5
- JS-Controller version: 4.0.23
- Node version: v16.16.0
- Operating system: Ubuntu 20.04.4 LTS

**Comment by Schmakus** [comment]
Adapter GUI wird komplett umgestellt. Die Entwicklung läuft.
