### ISSUE TITLE
Blinking also starts on "enable" transition from true->false

### ISSUE THREAD

**Issue by MichaelUray** [Schmakus/ioBroker.lightcontrol#61]
From my understanding the blinking should only start when the `enable` state gets set to `true`, but not when it gets set to `false`.

**To Reproduce**  
Change the `enable `state from `true `to `false`.

**Expected behavior**  
Blinking should not start.
Maybe it would also be a good idea to set the enable state back to false when the blinking is finished.

**Versions:**  
 - Adapter version: 0.0.4

**Comment by Schmakus** [comment]
Enable is a Button to start the blinking, not for stopping. 
Maybe, I will check if an stop button is sensible.

**Comment by MichaelUray** [comment]
Maybe this would be a good way:
- To set `enable` starts blinking cycle.
- To clear `enable` stops running blinking cycle.
- When the blink amount is reached / blinking cycle is done, then `enable` gets cleared by the adapter.
  On this way you could also check by an application if the blinking cycle is running by checking the `enable` state.
- If blinking cycle is still in operation and `enable` gets set/triggered again, then restart blinking cycle from begin.

**Comment by Schmakus** [comment]
the following are implemented:
- `enable` start and stop infinity blinking
-  `start` (button) for blinking until amount is reached. 

Please test ist
