### ISSUE TITLE
autoOffLux auch wenn Lampe extern eingeschaltet wird

### ISSUE THREAD

**Issue by Tratonis** [Schmakus/ioBroker.lightcontrol#86]
Das wäre ein schönes Feature ohne den ganzen Raum vorher über den Power DP einschalten zu müssen.

**Comment by Schmakus** [comment]
Was meinst du damit?
Wieso soll eine Lampe von "extern" geschaltet werden, wenn der Adapter alle erledigt?

**Comment by Tratonis** [comment]
Beispiel Kinderzimmer:
Eine Deckenleuchte und ein lightstrip unterm Bett. Das Kind schaltet den Lightstripe abends mit Wunschfarbe und Wunschhelligkeit über Alexa (IOT Adapter) ein. Wenn es hell genug ist soll der Lightstripe und ggf falls auch die Deckenlampe aus gehen.
Alternativ könnte ich power der Gruppe im iot Adapter verwenden,  dann wäre aber jede Lampe eine eigene Gruppe.

**Comment by Eistee82** [comment]
Wenn der Lightstrip einzeln geschalten werden soll dann ist er nicht Bestandteil der Gruppe. Gruppen dienen dazu mehrere Leuchten gleich zu schalten. Also wenn du beispielsweise mehrere Lampen im Raum hast und alle dimmen oder hell willst. Evtl. sollte man aber noch darüber nachdenken ob der Adapter eine Lampe nicht auch mehreren Gruppen zuordnen können sollte. Ich denke z.B. an eine Lampe die sich an einer Hausecke befindet und an jeder Seite ein Bewegungsmelder ist der aber nur auf der Seite das Licht anschalten soll. Dann müsste eine Lampe mit 2 Gruppen schaltbar sein. Momentan müsste man für diese Lampe eine extra Gruppe anlegen die dann beide Bewegungsmelder hat.

**Comment by Schmakus** [comment]
Eine Lampe in mehreren Gruppen ist vorgesehen, aber aufgrund eines Bugs in jsonConfig nocht nicht möglich.
