### ISSUE TITLE
CT wird beim Einrichten mit Werten zwischen 0-100% eingerichtet, DPs werden aber mit HexWerten angelegt 

### ISSUE THREAD

**Issue by ch90045** [Schmakus/ioBroker.lightcontrol#89]
Nutze letzte Version.

Beim Einbinden eines Ikea Deckenfluter liegen aus Traedfri folgende DPs vor:

![image](https://user-images.githubusercontent.com/2450761/212298962-39333a35-0731-44aa-8705-481028deaf15.png)
Augenmerk auf CT.

Beim Einrichten des CT DPs für lightcontrol kann man Werte zwischen 0-100 nutzen:

![image](https://user-images.githubusercontent.com/2450761/212299260-cb8cc015-7f77-46fa-9a8e-02b4fd7b9792.png)

Im Lightcontrol DP Bereich wird aber nicht 0-100 genutzt sondern der Hex Wert bzw. die Farbtemperatur.

![image](https://user-images.githubusercontent.com/2450761/212298723-6964d6e4-eb51-4b1d-ac47-a1b0f7b45637.png)

So lässt sich CT leider nicht steuern

**Comment by Schmakus** [comment]
Das ist richtig so!
LightControl arbeitet nur mit Kelvin Werten. 2700 K = warmweiß, 6500K = Kaltweis (Kelvin min und Max sind in dem Instanzeinstellungen zu definieren)
In deinem Fall musst du in den Eintellungen deines CT Datenpunkts deiner Lampe als min-Wert=100 und Max-Wert 0 manuell festlegen. Also umgekehrt. 
Aber die Frage ist gut, werde es entsprechend anders Formulieren, bzw. in der Doku ggf. anpassen.

**Comment by ch90045** [comment]
Ne, das klappt nicht - der CT Wert wird nicht genommen bzw. das ganze loopt sogar.  Wenn ich das richtig sehe, schliesst das alle Traedfri Geräte mit CT Werten von Lightcontrol aus.

Vom loopen habe ich ein Video gemacht - es wird immer von 9% zu 80% hoch gedimmt und wieder von Vorne begonnen.

**Comment by Schmakus** [comment]
Ok, schau ich mir an. 
BTW: stell mal das Logging des Adapters auf "Debug", ändere anschließend den ct Wert der Gruppe und poste anschließend den Log hier, danke.

**Comment by Schmakus** [comment]
@ch90045 Hallo, ich habe es getestet und konnte es nicht reproduzieren.
Wenn Power = true, werden alle Parameter sauber an die Lampen übertragen. 
Für eine Fehlersuche bei dir ist der Debug-Log unabdingbar!

**Comment by Schmakus** [comment]
Ich hab dein Problem glaube ich nun verstanden. In der nächsten Version wird es bei den Farbtemp. Einstellungen einen Switch geben, um Warm- und Kaltweiß umzukehren. Also anstatt z.B. 100 = Kalt, wird dann 100 = Warm sein.

**Comment by ch90045** [comment]
Cool
